---
# To be used in a workflow to rollback config to the original backup
- name: Load config from file
  hosts: "{{ target_host_name }}*"
  connection: local
  gather_facts: no

  vars:
    - backup_path: "/tmp/fortinet-backup"
    - backup_filename: "stable_fortigate-01_20200830-1200.conf"

  tasks:
  - name: Restore current config from previous backup
    fortios_config:
      host: "{{ ansible_host }}"
      username: "{{ fg_username }}"
      password: "{{ fg_password }}"
      # Mock up restore - forcing this one particular file
      src: "/tmp/fortinet-backup/stable_fortigate-01_20200830-1200.conf"
...
