---
- name: Upload backup config file to FTP server
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - backup_path: "/tmp/fortinet-backup"
    - backup_filename: "backup_fortigate-01_20200913-1059.conf"
    - stable_filename: "stable_fortigate-01_20200913-1100.conf"
    - ssh_user: "feliz"
    - ssh_password: "supersecret"
    - ftp_server: "62.240.177.100"
    - ftp_path: "/home/feliz/ftp/fortinet"

  tasks:
  - name: upload config file
    command: sshpass -p {{ ssh_password }} scp -o StrictHostKeyChecking=no {{ backup_path }}/{{ backup_filename }} {{ ssh_user }}@{{ ftp_server }}:{{ ftp_path }}/{{ stable_filename }}
...
