---
- name: Compare backup file to the latest stable config
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
  - backup_path: "/tmp/fortinet-backup"
  - backup_filename: "backup_fortigate-01_20200913-1500.conf"
  # gets stable config from FTP Server
  - ftp_server: "62.240.177.100"
  - ssh_user: "feliz"
  - ssh_password: "supersecret"
  - stable_path: "/home/feliz/ftp/fortinet"
  - stable_filename: "stable_fortigate-01_20200830-1200.conf"

  tasks:
  # Get the latest stable configs from github
  - name: get stable config file (last good known config)
    command: "sshpass -p {{ ssh_password }} scp -o StrictHostKeyChecking=no {{ ssh_user }}@{{ ftp_server }}:{{ stable_path }}/{{ stable_filename }} {{ backup_path }}/{{ stable_filename }}"

  # Must fix max_diff_size in ansible.cfg to support big file
  - name: compare backup against stable
    copy:
      src: "{{ backup_path }}/{{ backup_filename }}"
      dest: "{{ backup_path }}/{{ stable_filename }}"
    check_mode: yes
    diff: yes
...
