---
- name: Backup FortiGate Configuration
  hosts: "{{ target_host_name }}*"
  connection: local
  gather_facts: no

  vars:
    - fg_username: azureforti
    - fg_password: supersecret
    - backup_path: "/tmp/fortinet-backup"
    - backup_filename: "myfullbackup_file.conf"

  tasks:
  - name: copy configuration
    command: "sshpass -p {{ fg_password }} scp -o StrictHostKeyChecking=no {{ fg_username }}@{{ ansible_host }}:sys_config {{ backup_path }}/{{ backup_filename }}"
...
