---
# This module uses community fortios_config module
- name: Backup a part of running config
  hosts: "{{ target_host_name }}*" 
  connection: local
  gather_facts: no

  vars:
    - backup_path: "/tmp/fortinet-backup"
    - backup_filename: "{{ inventory_hostname }}"
    - filter: "firewall address"

  tasks:
  - name: Get timestamp from the system
    shell: "date +%Y%m%d-%H%M"
    register: tstamp
  - name: Set variables for timestamp
    set_fact:
      cur_date: "{{ tstamp.stdout }}"

  - name: Backup current config with filter
    fortios_config:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      backup: yes
      timeout: 60
      backup_options:
        dir_path: "{{ backup_path }}"
        filename: "{{ backup_filename }}_{{ cur_date }}.conf"
      filter: "{{ filter }}"
...
