---
# This module uses community fortios_config module
- name: Backup a part of running config
  hosts: "{{ target_host_name }}*" 
  connection: local
  gather_facts: no

  vars:
    - backup_path: "/tmp/fortinet-backup"
    - backup_filename: "mybackup_file.conf"
    - filter: "firewall address"

  tasks:
  - name: Backup current config with filter
    fortios_config:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      backup: yes
      timeout: 60
      backup_options:
        dir_path: "{{ backup_path }}"
        filename: "{{ backup_filename }}"
      filter: "{{ filter }}"
...
