---
- name: Compare backup file to the latest stable config
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
  - git_repo: "https://github.com/felizkk/fortinet-config.git"
  - git_path: "/tmp/github" 
  - backup_path: "/tmp/fortinet-backup"
  - backup_filename: "backup_fortigate-01_20200913-1500.conf"
  - stable_path: "/tmp/github/demo-stable"
  - stable_filename: "backup_fortigate-01_20200913-1100.conf"

  tasks:
  # Get the latest stable configs from github
  - name: clear websource directory
    file: 
      path: "{{ git_path }}"
      state: absent  

  - name: get the latest webpage source from git
    git:
      repo: "{{ git_repo }}"
      dest: "{{ git_path }}"

  # Must fix max_diff_size in ansible.cfg to support big file
  - name: compare backup against stable
    copy:
      src: "{{ backup_path }}/{{ backup_filename }}"
      dest: "{{ stable_path }}/{{ stable_filename }}"
    check_mode: yes
    diff: yes


...
