- name: Gather Facts from FortiGate
  hosts: "{{ target_host_name }}*" 
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no

  vars:
    - target_fact: "system_firmware_select"

  tasks:
  - name: gather basic system status facts
    fortios_facts:
      host:  "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      vdom:  "root"
      ssl_verify: no
      gather_subset:
        - fact: '{{ target_fact }}'
    register: result

  - debug:
      var: result.ansible_facts
