---
- name: Update System Global Settings
  hosts: "{{ target_host_name }}*"
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
 
  tasks:
  - name: Configure System Global
    fortios_system_global:
      host: "{{ ansible_host }}"
      username: "{{ fg_username }}"
      password: "{{ fg_password }}"
      ssl_verify: no
      vdom: "root"
      system_global:
        alias: "{{ inventory_hostname }}"
        hostname: "{{ inventory_hostname }}"
        timezone: "{{ timezone }}"
        admin_scp: "{{ admin_scp }}"
        admintimeout: "{{ admin_timeout }}"
...